# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Set environment variable to development
ENV NODE_ENV development
ENV TZ=Asia/Manila

# Start the application
CMD ["npm", "run", "dev"]
